### ISSUE TITLE
Add 0D solver to SimVascular

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#853]
Currently, the 0D solver is in its own (for now private) repository. To run the solver from within SimVascular (GUI or SV-Python), the solver source code (Python) should be included in SimVascular. I think this could be done via ```git submodule```.

**Comment by mrp089** [comment]
I think ```git submodule``` works well in our case since we have a "static parent-child repository relationship" between SimVascular and svZeroDSolver. However, this would require people to run ```git submodule update``` and ```git clone --recursive``` when getting the SimVascular source code. See, e.g., here: https://github.blog/2016-02-01-working-with-submodules/

**Comment by ktbolt** [comment]
I think this can be done in CMake.

**Comment by mrp089** [comment]
Great! Then I think we should import the 0D solver in ```Python/site-packages```.

**Comment by mrp089** [comment]
@osmsc I have no idea how to initiate the ```submodule update --init --recursive``` command with ```make```. Can you add that?

**Comment by ktbolt** [comment]
@mrp089 What commands are need to update submodules? 

I did 
```
git submodule update --init --recursive
```
but CMake keeps checking out the old GitHub svZeroDSolver version `1957df17333732fe5bf0ec0b63a3f9b5f3340118` Fri May 21 15:42:32 2021 -0700.

**Comment by mrp089** [comment]
The command to get the current master of the submodule is

```git submodule update --remote --merge```

What do you think is the best way to handle that in the repository? Manually bump up the version of svZeroDSolver or always pull the current master?

**Comment by ktbolt** [comment]
That worked, thanks!

We need to have control over which repository is used when doing development and building  a release. We could by default use master with an option to specify SHA or tag?

**Comment by mrp089** [comment]
I originally used the relative path ```../svZeroDSolver.git``` as the URL for the submodule. This avoids explicitly specifying the access mode (```HTTPS``` vs. ```SSH```) and uses whatever access mode the developer had chosen for the parent ```SimVascular``` git repository. 

@osmsc Is there a reason why this was changed to ```SSH``` (i.e. ```url = git@github.com:SimVascular/svZeroDSolver.git```) in a517379? This doesn't work if a developer uses ```HTTPS```.

**Comment by osmsc** [comment]
@mrp09 @ktbolt: I didn't see this thread originally when I started trying to get the submodule stuff to work.  When I started, the Travis build was broken so I was trying to get things to work.  Here is my understanding as of now:

* The .gitmodules included references to ParasolidSolidModel which (a) should have been deleted long ago, and (b) was killing the Travis build since this was a private repository not accessible to average users.   I removed the reference to ParasolidSolidModel from .gitmodules.

* The git submodule call was specifying a fatal error if it couldn't check out the 0D code, which seems extreme.  I switched this to a warning in CMake.
 
* The git submodule call was being done at the Toplevel CMake file although it more logically belongs in the SimVascular CMake since it's "SV code" and not external libraries like VTK (which is pulled iin the toplevel CMake).  I moved it down a directory and attempted to add a flag to let the user decide if they want to pull in the zerod code when building.  As always, passing the flag was cryptic in CMake so I eventually just set the flag to ON.

* Using the relative path in .gitmodules (@mrp089) meant that I couldn't build from my own fork of SV since I hadn't already forked the 0D solver.  I don't want to make forking the 0D solver repository a prerequisite for forking SV.  This is why I switched to a fixed path.

* Git submodules (according to the documentation I read) are intended for very stable code.  As far as I can tell, Git adds the hashtag somewhere in its magic database when you first add the submodule and then do a commit.  That's why it keeps checking out the May 4th version of the 0D code even though it has been significantly changed since then.  The best option I could find was the "--remote" flag to the submodule command which pulls out the head from the 0D code which should be fine if we are pulling from the core SimVascular repository.

* @mrp089:  Can you check and see if you are having problems still with the explicit path in .gitmodules after my commit from last night?  I screwed up the check for the .git directory after I moved the call down one directory, i.e.:

  ${PROJECT_SOURCE_DIR}/.git -> ${PROJECT_SOURCE_DIR}/../.git

Wait, I guess I put http in the file which worked for me.  I don't have a problem switching it https.  Will commit that now.

**Comment by mrp089** [comment]
@osmsc Thanks for sorting this out!

I cloned a pristine copy of SimVascular but it didn't pull the submodule when I ran ccmake (setting ```SV_GIT_PULL_SUBMODULES``` to ```ON```).

**Comment by osmsc** [comment]
@mrp089   Ugh, not sure what the issue is.  Can you check out a new copy, cd into the SV source directory, and try:

% git submodule update --init --recursive --remote

Manually and see if the command that runs.  Also, please check the cmake log:

There should be some output if the flag is set and git is found.  Here is the new code that is in Code/CMakeFiles.txt:

# add git submodules
if(SV_GIT_PULL_SUBMODULES)
  #message(STATUS "inside of SV_GIT_PULL_SUBMODULES")
  find_package(Git)
  message (STATUS "Checking if git repository: ${PROJECT_SOURCE_DIR}/../.git")  
  if(GIT_FOUND AND EXISTS "${PROJECT_SOURCE_DIR}/../.git")
  # Update submodules as needed
    message(STATUS "Submodule update")
    execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init --recursive --remote
                        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
                        RESULT_VARIABLE GIT_SUBMOD_RESULT)
    if(NOT GIT_SUBMOD_RESULT EQUAL "0")
            message(WARNING "git submodule update --init failed with ${GIT_SUBMOD_RESULT}, please checkout submodules")
    endif()
  endif()
endif()

**Comment by osmsc** [comment]
@mrp089 -- fyi: just checked master in SV repos and it seems to pull 0D code okay on Ubuntu 20.

**Comment by mrp089** [comment]
Strange... ```git submodule update --init --recursive --remote``` works as expected. But executing ```cmake -DSV_GIT_PULL_SUBMODULES=ON ..``` from ```./build``` (or setting the flag manually in ccmake) doesn't do anything. 

The flag is shown as ```ON``` in ```CMakeCache.txt```. However, there is no output (neither from ```STATUS``` nor from git).
