### ISSUE TITLE
0D: Solver crash not detected by GUI

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#922]
When the 0D solver crashes (with a Python exception) upon clicking `Run Simulation` in `ROMSimulation`, SimVascular shows `The 0D simulation has completed.` There is no error message like for the 1D solver. (To trigger a 0D solver crash, e.g. provide an inflow file with `100 100` as the only time step.)

**Comment by ktbolt** [comment]
The `run_from_c()` function in `svZeroDSolver/svzerodsolver/solver.py` needs to return a status, a string that says `ok` or `ERROR: Inflow file is not in the correct format', something that can be recognized by SV as a failure.

You will need to put a `try/except` block in `run_from_c()` to catch the inflow file exception and return its text.

**Comment by ktbolt** [comment]
I've added a `try/except` block in the `run_from_c()` function defined in `svZeroDSolver/svzerodsolver/solver.py` to return and error message, added processing this message in `sv4guiROMSimulationPython::ExecuteZeroDSimulation()`.

Now the following popup appears when things go wrong

<img width="891" alt="Screen Shot 2021-09-14 at 1 30 44 PM" src="https://user-images.githubusercontent.com/23109458/133330317-353fa6a2-025a-454f-8c23-f504d8bba402.png">


Note that this error was caused by a bad input flow file. Input should be checked and errors handled better in the svZeroDSolver code rather than producing a Python run time error that users can't decipher.

**Comment by ktbolt** [comment]
I've merged svZeroDSolver  and SV changes into master.

**Comment by mrp089** [comment]
I tested the current master (bdf2256) with [this example](https://drive.google.com/file/d/1cMVQmt5eAb19Q7Z74ElRs8FfUrQ5DgNM/view?usp=sharing). When I try to run the 0D simulation, SimVascular crashes with a segfault after successfully completing the simulation. Running the input file directly in`svZeroDSolver` seems to be fine.

**Comment by ktbolt** [comment]
I just tested and it worked fine. 

I also made changes to `svZeroDSolver` to return a status; maybe it did not update in your SV build? I was going to add code in SV to check to make sure `svZeroDSolver` did return a status but thought it would update automatically.

**Comment by mrp089** [comment]
Turns out I only did a `git pull` and not a `git submodule update --remote`. The difference is explained [here](https://stackoverflow.com/questions/19619747/git-submodule-update-remote-vs-git-pull/19621245#19621245).

Setting the global option in my git

```git config --global submodule.recurse true```

should do this automatically from now on.

**Comment by mrp089** [comment]
Works as expected!
