### ISSUE TITLE
0D: Add junction modeling

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#948]
Currently, our 0D (and 1D) ROMs ignore pressure changes at junctions. @natalia-rubio started implementing two junction models in https://github.com/SimVascular/svZeroDSolver (based on mynard15 and a custom Neural Network model) and needs information on junctions passed to the 0D input files.

@natalia-rubio can you list what information you need for which junction? Thanks!

**Comment by natalia-rubio** [comment]
For the DNN: 
  - area
  - direction change
  - junction length
  - flow time derivative

For the Unified0D model (mynard15):
  - area
  - direction change

**Comment by mrp089** [comment]
Thanks! Some clarifications:

- `flow time derivative` needs to come from the solution, not the input file
- `area` for inlet and outlets?
- `junction length` and `direction change (angle)` for all outlets?
- `direction change (angle)` angle between inlet and outlet normal vector in radians?

**Comment by natalia-rubio** [comment]
Yes to all!  

- I removed to flow time derivative.  
- If possible, I think the easiest would be to provide separate arrays for area, junction length, and direction change for each branch in the same order that the branches are listed in the "flow directions" vector.  Since junction length and direction change don't make sense for the inlets, maybe you could put a NaN or something similar for those entries?
- Yes, direction change is the angle between inlet and outlet normal vectors in radians.
- I'm not sure what we should do with the DNN in cases where there are multiple inlets. (Compute pressure loss from each inlet and average the results?)  Maybe for now we can just set those to 0 and figure out the handling for this case later?

**Comment by mrp089** [comment]
This functionality was merged in #969. I'll close this for now. Please reopen if you need more information from junctions in the 0D input file.
